### ISSUE TITLE
Update to react-native-keychain V6.0.0 breaks hasUserSetPinCode and other methods

### ISSUE THREAD

**Issue by greenbue** [jarden-digital/react-native-pincode#137]
v6.0.0+ of react-native-keychain breaks the method hasUserSetPinCode because of its reliance to Keychain.getInternetCredentials

Instead of 
```
Keychain.getInternetCredentials('reactNativePinCode')
```

Authentication Prompt needs to be declared.
https://github.com/oblador/react-native-keychain/releases/tag/v6.0.0
```
Keychain.getInternetCredentials('reactNativePinCode', { authenticationPrompt: { title: 'prompt' } })
```

Error returned
```
PinCodeEnter:  [Error: Title must be set and non-empty]
```

**Comment by efronnyp** [comment]
@greenbue +1 for this issue. I faced exactly the same issue as yours sometimes ago.
From what I got:

1. It is actually `react-native-keychain` bugs as the author claims that the default value of the `authenticationPrompt.title` is `Authenticate to retrieve secret` (kindly see this [section](https://github.com/oblador/react-native-keychain#authenticationprompt-properties)). However, if you dive into `KeychainModule.java` file, and goto `getPromptInfo()` [function](https://github.com/oblador/react-native-keychain/blob/master/android/src/main/java/com/oblador/keychain/KeychainModule.java#L541), you will see that there is no `setTitle()` nor `setNegativeButtonText()` called (which are required to build the PromptInfo) if the `options` is `null`. Thus make the PromptInfo building process throw an exception.
2. In my case, I just invoke `Keychain.getInternetCredentials(...)` manually, and pass the
`{ authenticationPrompt: { title: "Fingerprint title", cancel: "Cancel" }}` options.
3. It is also good to raise this issue on `react-native-keychain` repository if it's not raised yet

So in my opinion, the best way to solve this issue is by manually invoke the `getInternetCredentials` function, and recommend a resolution to `react-native-keychain` regarding this issue.

I hope it helps you.

**Comment by greenbue** [comment]
@efronnyp - Thanks for the feedback, I will definitely try your suggestions.

Upon further investigation - it does seem to be more of an issue on ``react-native-keychain`` - as you have mentioned, the default title seems to be missing after they deprecated the old way of setting up authenticationPrompt.

![image](https://user-images.githubusercontent.com/7563673/79315440-0b7f5d00-7f57-11ea-86c1-e4bd73da81a0.png)

**Comment by greenbue** [comment]
https://github.com/jarden-digital/react-native-pincode/blob/2b3e4a33d2af2344f5272a73274c096fd2687a2f/dist/src/PinCodeEnter.js

This method will now throw an error because of...

> However, if you dive into KeychainModule.java file, and goto getPromptInfo() function, you will see that there is no setTitle() nor setNegativeButtonText() called (which are required to build the PromptInfo) if the options is null. Thus make the PromptInfo building process throw an exception.

PinCodeEnter is using ``Keychain.getInternetCredentials(...)`` without the declaration of authenticationPrompt and title.

**Comment by Haskkor** [comment]
Just merged. Releasing a new version in a few minutes.
Thanks!
