### ISSUE TITLE
Unable to style the library?

### ISSUE THREAD

**Issue by EmilMakaev** [jarden-digital/react-native-pincode#166]
I try to style, for example, I write:

`styleLockScreenMainContainer={styles.container}`

```
const styles = StyleSheet.create({
  container: {
    backgroundColor: '#000',
  },
});
```

Nothing works. What am I doing wrong? Tell me please.

**Comment by omorkved** [comment]
Instead of using a StyleSheet, try putting the desired styles directly into the brackets by using double brackets `styleLockScreenMainContainer = {{...}}`

examples from code that I've been running:

`stylePinCodeMainContainer={{backgroundColor:'#000', paddingBottom:0, marginBottom:0}}`

`stylePinCodeButtonCircle={{borderRadius: 8, width: screenWidth/3.5, height: screenHeight/12, 
                                          borderColor: "black", borderWidth: 0.5, backgroundColor:"white"}}`

This worked for me.

**Comment by EmilMakaev** [comment]
> Instead of using a StyleSheet, try putting the desired styles directly into the brackets by using double brackets `styleLockScreenMainContainer = {{...}}`
> 
> examples from code that I've been running:
> 
> `stylePinCodeMainContainer={{backgroundColor:'#000', paddingBottom:0, marginBottom:0}}`
> 
> `stylePinCodeButtonCircle={{borderRadius: 8, width: screenWidth/3.5, height: screenHeight/12, borderColor: "black", borderWidth: 0.5, backgroundColor:"white"}}`
> 
> This worked for me.

Thank you very much!
